### ISSUE TITLE
"linkify URI strings in plain text" causes tb5 not show valid links properly

### ISSUE THREAD

**Issue by LeeDailey** [piroor/textlink#10]
howdy y'all,

in thunderbird 5.0 with text link v-4.0.2011021601 if you enable "linkify URI strings in plaint ext messages" [the default], tbird stops showing valid text links as links. normally, the links are blue and respond to a single click. when TL is enabled and that [default] option is enabled, the links be come simply text and require a double click to activate.

this was not the case with tbird 3.1.11 and the same version of TL.

take care,
lee

**Comment by piroor** [comment]
Outdated.
