### ISSUE TITLE
TL ignores URLs with unqualified hostnames

### ISSUE THREAD

**Issue by shalomb** [piroor/textlink#13]
URLs with hostnames that are not qualified such as the following are not recognized by TL.

http://example/about
http://localhost/index.html
http://localhost/

TL behaves as normal when the same hostnames are made more "domain-like" or are better qualified, like the following.

http://example.org/about
http://localhost.localdomain/index.html
http://localhost.localdomain/

**Comment by piroor** [comment]
Outdated.
