### ISSUE TITLE
Bind menu items with menupopup in content-area context menu

### ISSUE THREAD

**Issue by saneyuki** [piroor/textlink#17]
If user enables textlink's menu items of a content-area context menu, opening the context menu is too slow on some pages. (e.g. https://github.com/piroor/textlink/blob/master/modules/utils.js)

This bug is caused by searching URIs on opening the context menu.
But user does not always use textlink's context menu.

So I propose that, binding textlink's menu items with menupopup in content-area context menu.
This approach can delay the timing of searching URIs.

**Comment by piroor** [comment]
Done. Thank you for your suggestion!
