### ISSUE TITLE
zombie compartments

### ISSUE THREAD

**Issue by tawxazle** [piroor/textlink#20]
In current firefox 15 nightly your extension causes zombie compartments.

Steps to reproduce:
1. double click plain text link on 
http://piro.sakura.ne.jp/xul/textlink/index.html.en#testcases
2. close all tabs
3. go to about:compartments

Second case, Steps to reproduce:
1. Go to
http://piro.sakura.ne.jp/xul/textlink/index.html.en#testcases
2. Select all from edit menu
3. right click selection to bring up context menu
4. close all tabs
5. go to about:compartments

**Comment by piroor** [comment]
about:compartments seems not available on the current Firefox 43. Is there any way to confirm reproduced problem?

**Comment by piroor** [comment]
Outdated.
