### ISSUE TITLE
Script does not respond or so error in Thunderbird

### ISSUE THREAD

**Issue by Aladincz** [piroor/textlink#28]
Hello,

I am getting this kind of error on one type of message that contains txt attachment. It renders in message and cause that TB does not respond for about 30 seconds and then shows error message to wait or end script.
It offers option not to ask again but I have not tried it yet. Not to loose add on functionality.

Error is in my language but may help:
Skript na této stránce je buď zaneprázdněn nebo přestal reagovat. Nyní můžete skript ukončit nebo počkat, zda se dokončí sám.

Skript: file:///C:/Documents%20and%20Settings/Administrator/Data%20aplikac%C3%AD/Thunderbird/Profiles/w8xescg0.default/extensions/%7B54BB9F3F-07E5-486c-9B39-C7398B99391C%7D/modules/utils.js:746

screen is here http://dl.dropbox.com/u/610163/errortext2link.jpg

Txt file is bigger, 164 Kb. At the end it contain on active email address and one inactive text url. And contains some strange characters as is seen on screen shot.

Hope it can be enough to deal with it.

Thanks a lot

Frantisek

**Comment by piroor** [comment]
I also see this problem sometimes...

Just an idea, "viewport-based" linkification possibly solves this problem. If only text nodes included in the viewport are linkifyed at once, they you won't have to wait for the completion of linkification for whole the page.

**Comment by piroor** [comment]
But I don't know how implement it...

**Comment by piroor** [comment]
Outdated.
