### ISSUE TITLE
URIs with three slashes after the protocol name (e.g. evernote:///view/<something>) are not recognized by Text Link

### ISSUE THREAD

**Issue by egoexpress** [piroor/textlink#35]
Tools like [Evernote](http://www.evernote.com) generate URIs containing three slashes after the protocol name (evernote:///). Example:

evernote:///view/252711/3/a70666-e544-48cc-9fa3-90a98dbb2f/a70666-e544-48cc-9fa3-190a98dbb2af/

Text Link doesn't recognize those URIs. When I remove a slash, i.e. the above URI becomes

evernote://view/252711/3/a70666-e544-48cc-9fa3-90a98dbb2f/a70666-e544-48cc-9fa3-190a98dbb2af/

Text link works once again.

**Comment by piroor** [comment]
Hmm, simply allowed three slashes pattern possibly break other behaviors for me...
https://github.com/piroor/textlink/tree/allow-three-slashes

**Comment by piroor** [comment]
Outdated.
