### ISSUE TITLE
can't open link with line break

### ISSUE THREAD

**Issue by GiftWolf** [piroor/textlink#36]
I have problems with links on this website: http://www.heise.de/newsticker/foren/S-Details-hier/forum-268533/msg-24324553/read/

even when I select both lines and do a right mouse click and click "Open in new tab..." Text link will only open the first line of selected text.

**Comment by piroor** [comment]
As described at https://github.com/piroor/textlink/issues/41#issuecomment-167217468 this can't be fixed.

**Comment by GiftWolf** [comment]
OK, but shouldn't all selected text be treated as part of the URL?

**Comment by piroor** [comment]
Outdated.
