### ISSUE TITLE
Ignore some character

### ISSUE THREAD

**Issue by AMZMA** [piroor/textlink#40]
how can I ignore some character?
like "*" or "!"(without quotes)

exmpl
http://www.face**book.com => http://www.facebook.com

**Comment by piroor** [comment]
Those special characters possibly use to replace an existing character like `http;//f*ceb**k.com`, so it can open wrong URL if I simply ignore invalid characters in the domain part. For safety I think I should not do this.

Moreover, there is another problem. Currently this addon finds possible-URL strings based on a regular expression. If you hope to detect any URL-like string including invalid as a URL, a new regular expression will match to any strings, then we'll lost the way how to detect the string is a URL or not. I can't imagine how to do it smartly...

Anyway, if you have an break-through idea for implementation, please send a pull request me.

**Comment by piroor** [comment]
Outdated.
