### ISSUE TITLE
Multiple-line URL not linkified

### ISSUE THREAD

**Issue by orschiro** [piroor/textlink#41]
Hi @piroor 

Thanks very much for `textlink`. I installed it in the hope to have some long, over multiple-lines stretched, URLs linkified and clickable.

Therefore I enabled both options:

```
Linkify URI strings in plain text messages
Parse URIs split in multiple lines (unrecommended)
```

However, some URLs are still not linkified. Particularly the ones from CouchSurfing.

Excerpt from the email:

```
RESPONSE LINK: http://www.couchsurfing.org/send_message.html?id=6N5SV85&mid=1P8CX22Y5&utm_campaign=message&utm_medium=email&utm_source=cs
```

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/170947/4782545/8c7f2ae6-5cfa-11e4-93a5-d11ad68b3c53.png)

Any idea how I can linkify them?

Thanks ahead!

Robert

**Comment by piroor** [comment]
I think this couldn't be fixed forever, because there is no way to detect whether the next line is continued part of the URL or not...

**Comment by orschiro** [comment]
Thanks for your response @piroor!

**Comment by piroor** [comment]
Outdated.
