### ISSUE TITLE
Does not work on Firefox 37.0.1  32 bit

### ISSUE THREAD

**Issue by fsieber** [piroor/textlink#47]
Probably same problem as reported in Jan, etc.    Possibly competing add ons installed:  CoLT, Local Link, Copy Plain Text 2, Copy on Select.  But these all worked together fine on previous versions of FIrefox.

**Comment by yfdyh000** [comment]
Is #45 or de5d09748bf095b6e2b053d4fb066fd7ee34460c fixed it, but @piroor still don't publish it to AMO...

Try the https://github.com/tejanium/textlink/raw/437c553d663a4b01c51c41b081acbabfc1aeec1b/textlink.xpi build.

**Comment by fsieber** [comment]
The fix mentioned above cured the problem for me, even with the other related addons installed.  Thanks, I use this on a lot.

**Comment by urbanhusky** [comment]
This is *slightly* annoying. I really like this addon, please fix it. I don't want to search for another and then completely forget about this one :(

**Comment by p1nkyy** [comment]
Piro-san, please update and fix this add-on, nothing is as good as yours!

**Comment by dogancelik** [comment]
I'm looking forward to this update :smiley: (using Firefox 38 Beta)

**Comment by pombreda** [comment]
@piroor Dear Piro-San, would you be kind enough to make a release on AMO? Life is sad without textlink!
Thank you!

**Comment by applepig** [comment]
Tested with Firefox 38.0.1.

The build @yfdyh000 provided works.

**Comment by p1nkyy** [comment]
Official Text Link released by @piroor:
http://piro.sakura.ne.jp/xul/textlink/index.html.en#download
or
https://addons.mozilla.org/en-US/thunderbird/addon/text-link/versions/ --> choose v5

**Comment by piroor** [comment]
This seems expired.
