### ISSUE TITLE
Open in foreground tab does not switch to the tab.

### ISSUE THREAD

**Issue by streetwolf** [piroor/textlink#49]
Running the latest version on Fx44.  I would think that opening the link in a foreground tab should also switch to it.  It acts exactly as a background tab.

Also, will text link be signed in the near future?

**Comment by piroor** [comment]
The development build http://piro.sakura.ne.jp/xul/xpi/nightly/ works for me. Could you try it? Note, you'll need to turn `xpinstall.signatures.required` to `false`.

**Comment by streetwolf** [comment]
The development build works fine.  Thanks.
