### ISSUE TITLE
URLs with inline passwords no longer work

### ISSUE THREAD

**Issue by meeztor** [piroor/textlink#5]
Since the upgrade to the 4.x series of textlink urls(ftp, http etc) with the user/pass inline no longer work. They always have worked in all previous builds. I have FTP and web servers that I manage and this extension is a great time saver.
Example:
http://user:pass@google.com
If you double click on this with "Parse IDN" enabled then only the "google.com" portion of the link gets selected and opened. If you disable Parse IDN then "pass@google.com" gets selected and opened. In previous builds the entire string would get selected and log you in to the ftp. I have tried all combination of settings and none of them seem to work.
Thanks

**Comment by piroor** [comment]
Outdated.
