### ISSUE TITLE
[improvements] "Open All in New Tabs"

### ISSUE THREAD

**Issue by tyaremco** [piroor/textlink#51]
**1)** A modification to the context menu item [Open All in New Tabs](https://github.com/piroor/textlink/blob/2e828cc2cea605b0c81ced259b74d53e993f2b82/locale/en-US/textlink/textlink.dtd#L43)

| text selected? | behavior |
| --- | --- |
| yes | open all URLs in selected text |
| no | ~~menu item hidden~~<br/>_open all URLs in clipboard text_ |

Opening URLs from the clipboard would be very useful when needing to open a list of URLs stored outside of the browser.  

**2)** The context menu item "Open All in New Tabs" should open tabs in an unloaded state (ie. in the same way as the Firefox option "Don't load tabs until selected"). This would greatly speed up the process of opening multiple tabs at once.

**Comment by piroor** [comment]
Clipboard feature seems out of purpose of this addon. I think this should be tracked by other addon for the purpose like https://github.com/piroor/observeclipboard

**Comment by piroor** [comment]
Outdated.
