### ISSUE TITLE
[Request] Use Text Link on white listed websites only

### ISSUE THREAD

**Issue by Chilius** [piroor/textlink#53]
Hello,

First i want to thank you for this addon, it saved me a lot of time using it.

My request:
Is it possible to add a white list to the addon so it only works on websites you put on the list?
I use this addon a lot, but only on a few websites. On the other 98% of the websites i visit, i don't need it.

The PC i use is still a powerful machine (Win 7 64 / i7 3770K / 16GB RAM) although it's a few years old, but lately i notice web browsing is getting slower and slower with all the addons running in the background of Firefox. Specially on websites that contain lots of texts.
So i think it's not a bad idea to have some addons that can put themself in stand-by mode when you don't need them. Sure i can turn off an addon manually if i don't need it, but it's more practical if the addon can do it by itself.

I know if i was only using Text Link it would hardly make a difference, but in combination with other text searching and weblink cleaning addons i think it will make web surfing faster if it doesn't search for URI texts when i don't need it.

**Comment by piroor** [comment]
Outdated.
