### ISSUE TITLE
Double-clicking a paragraph opens text links elsewhere in the same paragraph

### ISSUE THREAD

**Issue by Njol** [piroor/textlink#54]
Sometimes this extension opens a new tab when I'm selecting text (I often double click to select, as that allows to select whole words at a time which makes selecting text easier).

Suggested fix: after finding a link, check whether the cursor is actually over the link or not and abort if the cursor is outside. If this is not 100% accurate, you can just leave it as it is, as it's better to open more links than less IMHO.

PS: I really like your addon, even with this minor flaw :)

**Comment by piroor** [comment]
Outdated.
