### ISSUE TITLE
broken on v52.0a2 aurora

### ISSUE THREAD

**Issue by mausalimi** [piroor/textlink#56]
https://github.com/piroor/textlink/commit/72fb63c49f865ca3685485f2c9514641d7339d11

this breaks compatibility with v52.0a2
double clicking a textlink doesn't do anything now, i went back to the older build which does work fine here.

thanks. :)

**Comment by piroor** [comment]
Thanks. Seems to be fixed by recent commits.

**Comment by mausalimi** [comment]
a quick test was successful. probably a more thorough test isn't really needed in this case.
daily use will tell anyway. :)

thanks a lot.

**Comment by piroor** [comment]
Outdated.
