### ISSUE TITLE
Not working in Thunderbird

### ISSUE THREAD

**Issue by despecial** [piroor/textlink#57]
No effect when double clicking a text link.
Does this even support TB?

**Comment by kswartz26** [comment]
Pinging this one. I had it working fine in Thunderbird 52.9.0 with version 5.0.2, but it is no longer working in Thunderbird 60 with either 5.0.2 or 6.0.2. Looks like it needs to be updated for the change to how addon settings are done, because the addon is not listed under Add-On Options in TB 60.

**Comment by kswartz26** [comment]
Tried to manually set options (copying from previous install), turned on debug -- only got this in the Console window:

`Tue Oct 02 2018 15:59:39 GMT-0700 (Pacific Daylight Time) CH: messagePaneBoxFocus start
Tue Oct 02 2018 15:59:39 GMT-0700 (Pacific Daylight Time) CH: messagePaneBoxFocus stop
Tue Oct 02 2018 15:59:39 GMT-0700 (Pacific Daylight Time) CH: messagePaneBoxFocus start
Tue Oct 02 2018 15:59:39 GMT-0700 (Pacific Daylight Time) CH: messagePaneBoxFocus stop`

**Comment by piroor** [comment]
Outdated.
