### ISSUE TITLE
Text Link add-on inserts all lazy browsers on startup

### ISSUE THREAD

**Issue by mzso** [piroor/textlink#58]
Hi!

Based on my logs a Firefox developer determined that Text link causes this, which results in all content processes being created prematurely and pointlessly. With a potentially massive impact on memory usage and startup performance.

> The add-on should listen to the TabBrowserInserted event rather than the TabOpen event.

https://bugzilla.mozilla.org/show_bug.cgi?id=1360148

**Comment by piroor** [comment]
Outdated.
