### ISSUE TITLE
[Legacy] yield in strict mode

### ISSUE THREAD

**Issue by pintassilgo** [piroor/textlink#63]
58.0b1

I would like to keep the legacy version for use it in internal pages, like `view-source:` (I'm using dozens of legacy addons in Fx 58, including TST).

I've already fixed things like `nsIPrefBranch2` -> `nsIPrefBranch` and `for each` -> `for ... of`, but I coudn't solve the `yield` thing.

Fx 57 enforces strict mode, so I tried to change from
`getURIRangesIterator : function(aFrameOrEditable, aMode, aStrict, aExceptionsHash, aContinuationChecker)`
to
`getURIRangesIterator : function*(aFrameOrEditable, aMode, aStrict, aExceptionsHash, aContinuationChecker)`
And the same in `getURIRangesIteratorFromRange`.

But it seems that this isn't enough.

I also tried to replace `iterator.next()` by `iterator.next().value`, but still unsuccessful.

Could you tell what is wrong? Thank you.

**Comment by piroor** [comment]
Outdated.
