### ISSUE TITLE
When it returns to the original page after linking it becomes white

### ISSUE THREAD

**Issue by WhiteHawk-taka** [piroor/textlink#65]
## Short description
Text Link で別タブに移った後元のページに戻ると白いタブになっている

## Steps to reproduce
https://twitter.com/hikaru__m/status/988793192920182784

 1. Start Firefox with clean profile.
 2. Install Text Link.
 3. open [https://twitter.com/foxkeh/status/1912017221](https://twitter.com/foxkeh/status/1912017221)
 4. link http://party.mozilla.gr.jp/party10/
 5. back step 3 tab.

## Expected result
show page

## Actual result
show white page(It can be seen after a while)

## Environment

 * Platform (OS): macOS 10.12.6, Windows10 1709
 * Version of Firefox: 59.0.2
 * Version (or revision) of Text Link: 6.0.1

**Comment by piroor** [comment]
調査の結果、この問題はTwitterのWebページにテキストノードが大量にある事が原因であることが分かりました。
このURLをダブルクリックしたあと、URLのRangeとして
`{"framePos":0,"text":"http://party.mozilla.gr.jp/party10/","startTextNodePos":19693,"startOffset":15,"endTextNodePos":19693,"endOffset":50}`
という情報が取得されています。
これに基づいてURLの部分を表すRangeを作り選択範囲にするにあたって、`descendant::text()[count(preceding::text())=19693]`のようなXPath式を評価してテキストノードを特定しているのですが、これに時間がかかっているせいでフリーズしているという状況でした。
DOM3 XPathを呼んだ時点でC++の実装に処理を任せることになるのでそんなに時間はかからないだろうと思っていたのですが、まさかここまで遅いとは……

**Comment by piroor** [comment]
式を`descendant::text()[position()=${19693+1}]`に改めたらここまで時間がかかることはなくなりました。
`position()`は兄弟ノードの中での位置を表す物と思っていたのですが、`descendant::text()`の集合の中での位置ということだったのですね。ずいぶん長いこと誤解していました。

**Comment by piroor** [comment]
be3cc52 で直ったはずです。

**Comment by WhiteHawk-taka** [comment]
ホワイトアウトすることなく、正常に動作することを確認しました。
他のノードが多いページでの動作改善も期待されそうな内容で嬉しいです。
これからも引き続き使わせていただきます。ありがとうございました。
