### ISSUE TITLE
Incompatible with HighlightAll

### ISSUE THREAD

**Issue by WHRoeder1** [piroor/textlink#66]
Doesn't work with Highlightall 2.1 enabled.
https://addons.mozilla.org/en-US/firefox/addon/highlightall

## Environment

 * Platform (OS): 
Win10
 * Version of Firefox: 
61.0
 * Version (or revision) of Text Link: 
6.0.1

**Comment by piroor** [comment]
The addon Highlightall modifies selection ranges in the webpage. When you double-clicked a text in a webpage, the addon calls `selection.addRange()` without `selection.removeAllRanges()`. As the result there are two ranges internally. After that Text Link tries to detect double-clicked location from selection ranges, but the operation expects there is only one range. As the result, Text Link ignores the selection as an invalid status.

So I think that the addon must call `selection.removeAllRanges()` before `selection.addRange()`. This is a bug of Highlightall itself.

However, after I've applied a patch to my local version of Highlightall, Text Link still reports an error. So still I need more research...

**Comment by piroor** [comment]
I've realized that Text Link's operation was failed because Highlightall modifies page contents while Text Link's operation is in progress. By the commit 0878a02 now Text Link retries to find clicked URI text while 500msec.

The conclusion is: this conflict of Text Link and Highlightall need to be fixed by both sides. Text Link's problem has been fixed by recent changes, and Highlightall still need to be changed.

**Comment by piroor** [comment]
I've sent a message to the author of Highlightall, as:

```
Hello, I'm the author of the addon Text Link:
https://addons.mozilla.org/firefox/addon/text-link/

Here is a bug report about conflict of Text Link with your Highlightall.
https://github.com/piroor/textlink/issues/66

After I researched I've realized that Highlightall modifies selection ranges of the page. It calls "selection.addRange()" without "selection.removeAllRanges()", as the result the page unexpectedly have multiple selection ranges and Text Link treats the status as an invalid.
In general, we should call "selection.removeAllRanges()" before adding any range except cases intentionally producing multiple selection ranges (like multiple times Ctrl-drag in a webpages.)
Could you do this change to your Highlightall? I think this change will solve conflict of these two addons, moreover it will solve future conflict with other addons or any webpage scripts.

regards,
```

**Comment by J3r0m** [comment]
@piroor  I am the developer of HighlightAll extension. Your suggestion will be included in the next version of the extension.

**Comment by piroor** [comment]
Thanks!
