### ISSUE TITLE
Slowness with real-time search/filter box

### ISSUE THREAD

**Issue by AZ4x** [piroor/textlink#69]
I've been a long user of this very useful addon. For the past years I noticed Textlink sometime causing slowness/input lag when entering or deleting texts in serach box that shows results real-time in a drop down menu.
A good example would be Reddit (not in legacy mode). I cant remember but there were a few other sites that I came across in the past that had the same issue too.
I feel like it happens more when the results include more than just a simple text. If you compare the real-time search results from Reddit to something like Google search suggestion, you can get the idea what I mean by simple text.
Could it be something that can be optimized?

**Comment by piroor** [comment]
Thanks, the commit 1b081d7 should fix this problem. Now event handling is throttled and keys are ignored except the Enter key.
