### ISSUE TITLE
Performance problems with context menu

### ISSUE THREAD

**Issue by IByte** [piroor/textlink#7]
When selecting a lot of text and invoking the context menu (e.g. when copying the entire page - I do this a lot when copying spam from Gmail into SpamCop), the context menu can take several seconds to appear; only then can I finally get to e.g. the regular Copy command. The problem/delay does not occur when all of Text Link's additions to the context menu are turned off in the options dialog.

**Comment by piroor** [comment]
Basically this addon is designed for "lazy" people who don't want to select URL text carefully. The CPU spike is in exchange for its generosity. Of course I don't like needless high CPU usage - current heaviness is introduced from my poor programming skills. Patches for optimization are strongly wanted.

**Comment by piroor** [comment]
Outdated.
